version: "3"
services:
  nginx:
    ports: 
      - "3000:80"
      
  node-app:
    build:
      context: .
      args: 
        NODE_ENV: development
    volumes: 
      - ./:/app
      - /app/node_modules
    environment: 
      - NODE_ENV=development
      - MONGO_USER=rashotech
      - MONGO_PASSWORD=tunde4real
      - SESSION_SECRET=retsydufioigyftdrnetyuiofidks75urjtikitxuzryet
    command: npm run dev